version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: pmsystem2-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Anduongb67
      POSTGRES_DB: pmsystem2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infrastructure/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d pmsystem2" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
